export const modules = [
  { id: "day", label: "Meu dia", group: "HOME" },
  { id: "home", label: "Visão geral", group: "HOME" },
  { id: "inbox", label: "Caixa de entrada", group: "HOME" },
  { id: "tasks", label: "Tarefas", group: "PLANEJAR" },
  { id: "calendar", label: "Calendário", group: "PLANEJAR" },
  { id: "planner", label: "Planejar meu dia", group: "PLANEJAR" },
  { id: "projects", label: "Projetos", group: "PLANEJAR" },
  { id: "goals", label: "Metas", group: "PLANEJAR" },
  { id: "notes", label: "Notas", group: "ORGANIZAR" },
  { id: "habits", label: "Hábitos", group: "ORGANIZAR" },
  { id: "focus", label: "Foco", group: "ORGANIZAR" },
  { id: "finance", label: "Centro financeiro", group: "FINANÇAS" },
  { id: "review", label: "Revisão da semana", group: "FINANÇAS" },
  { id: "favorites", label: "Favoritos", group: "ACESSO RÁPIDO" },
  { id: "recent", label: "Recentes", group: "ACESSO RÁPIDO" },
  { id: "templates", label: "Modelos", group: "SISTEMA" },
  { id: "automations", label: "Automações", group: "SISTEMA" },
  { id: "notifications", label: "Notificações", group: "SISTEMA" },
  { id: "modules", label: "Explorar", group: "SISTEMA" },
] as const;
export const quickTypes = [
  ["task", "Tarefa"],
  ["expense", "Gasto"],
  ["income", "Entrada"],
  ["note", "Nota"],
  ["event", "Evento"],
  ["habit", "Hábito"],
  ["goal", "Meta"],
  ["project", "Projeto"],
  ["inbox", "Guardar na Inbox"],
] as const;
